Add -Wno-unused-parameter to suppress warnings.
For example:
external/srtp/crypto/cipher/null_cipher.c:110:48: error: unused
parameter 'iv' [-Werror=unused-parameter]

Change-Id: Ieaacecd557f03bf4fe2a841aa9ef43a6b2a84c31